@baseUrl = http://localhost:5000/api
@userId = f13caca6-1d47-4d62-9083-9921357e1211
@user2Id = 96522f4a-88a3-49e9-a6ce-572e448ac73b
@tweetId = 22f963dd-8220-421e-8f06-9578fc6c733c

### SIGN UP 1

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Luis",
    "username": "luisdeolme",
    "email": "luisdeol@email.com"
}

### SIGN UP 2

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Luis 2",
    "username": "luisdeolme2",
    "email": "luisdeo2l@email.com"
}
###

GET {{baseUrl}}/users/{{user2Id}}

###


POST {{baseUrl}}/users/{{userId}}/tweets
Content-Type: application/json

{
    "content": "Testing..."
}

###

GET {{baseUrl}}/users/{{userId}}/tweets/{{tweetId}}

###

POST {{baseUrl}}/users/{{userId}}/tweets/{{tweetId}}/likes
Content-Type: application/json

{
    "likeUserId": "96522f4a-88a3-49e9-a6ce-572e448ac73b" 
}

###

POST {{baseUrl}}/users/{{userId}}/tweets/{{tweetId}}/retweets
Content-Type: application/json

{
    "retweetUserId": "96522f4a-88a3-49e9-a6ce-572e448ac73b" 
}

### 

DELETE {{baseUrl}}/users/{{userId}}/tweets/{{tweetId}}

### Follow User
POST {{baseUrl}}/users/{{userId}}/followees
Content-Type: application/json

{
    "followeeId": "e7ec2526-dfd1-441c-84be-78c7c3c0f42f"
}