@baseUrl = http://localhost:5000/api
@userId = 76a2d166-4ff0-435f-ae74-51e7d166fd24
@tweetId = fec74dfa-2ea0-469c-bb42-abfe474e38bc

###

GET {{baseUrl}}/users/{{userId}}/tweets/{{tweetId}}

###

POST {{baseUrl}}/users/{{userId}}/tweets
Content-Type: application/json

{
    "content": "Testing..."
}