@baseUrl = http://localhost:5000/api
@userId = 51cd2201-c7ce-4686-aac3-73c73428f540
@tweetId = 343d03ab-caf7-4395-85a7-36a8e781f6d1

###

POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Luis",
    "username": "luisdeolme",
    "email": "luisdeol@email.com"
}

###

GET {{baseUrl}}/users/{{userId}}

###


POST {{baseUrl}}/users/{{userId}}/tweets
Content-Type: application/json

{
    "content": "Testing..."
}

###

GET {{baseUrl}}/users/{{userId}}/tweets/{{tweetId}}
